### ISSUE TITLE
Retracted rule is not restored when the the engine is executed again

### ISSUE THREAD

**Issue by vamshi-tg** [hyperjumptech/grule-rule-engine#159] opened 2021-01-07 11:33 UTC
**Describe the bug**
Retracted rules are not restored when the engine is executed again. From the Retract method's documentation, I'm assuming that when we call the `engine.Execute(dataCtx, knowledgeBase)` the retracted rule should be restored. However, this is not happening.

**To Reproduce**
1.Run the following code
```
package examples

import (
	"fmt"
	"strconv"
	"testing"

	"github.com/hyperjumptech/grule-rule-engine/ast"
	"github.com/hyperjumptech/grule-rule-engine/builder"
	"github.com/hyperjumptech/grule-rule-engine/engine"
	"github.com/hyperjumptech/grule-rule-engine/pkg"
	"github.com/stretchr/testify/assert"
)

type ComputedInputs struct {
	Name string
	Bid  float64
	Rate float64
}

const Grl = `
	rule SampleRule "Hero/Honda" {
		When
			ComputedInputs.Name == "Hero" || ComputedInputs.Name == "Honda"
		Then
			Log("SampleRule");
			ComputedInputs.Bid = ComputedInputs.Rate;
			Retract("SampleRule");
	}
`

func TestItems(t *testing.T) {
	testData := []*struct {
		CI      *ComputedInputs
		WantBid float64
	}{
		{
			CI: &ComputedInputs{
				Name: "Hero",
				Rate: 10,
			},
			WantBid: 10,
		},
		{
			CI: &ComputedInputs{
				Name: "Honda",
				Rate: 10,
			},
			WantBid: 10,
		},
	}

	// Prepare knowledgebase library and load it with our rule.
	lib := ast.NewKnowledgeLibrary()
	rb := builder.NewRuleBuilder(lib)
	byteArr := pkg.NewBytesResource([]byte(Grl))
	err := rb.BuildRuleFromResource("Tutorial", "0.0.1", byteArr)
	assert.NoError(t, err)

	engine := &engine.GruleEngine{
		MaxCycle: 10,
	}
	knowledgeBase := lib.NewKnowledgeBaseInstance("Tutorial", "0.0.1")

	for i, td := range testData {
		t.Run(strconv.Itoa(i), func(t *testing.T) {
			dataCtx := ast.NewDataContext()
			err := dataCtx.Add("ComputedInputs", td.CI)
			assert.NoError(t, err)

			rules, _ := engine.FetchMatchingRules(dataCtx, knowledgeBase)
			fmt.Printf("\nNo. of matching rules: %d\n", len(rules))

			knowledgeBase := lib.NewKnowledgeBaseInstance("Tutorial", "0.0.1")
			err = engine.Execute(dataCtx, knowledgeBase)
			assert.NoError(t, err)
			assert.Equal(t, td.WantBid, td.CI.Bid)
		})
	}
}

```

**Expected behavior**
All the tests should pass

**Additional context**
The tests are passing if we create a new instance of knowledgeBase on every execution. Do we have to create a new instance of knowledge base whenever a rule is retracted?

**Comment by newm4n** [comment] 2021-01-09 02:28
Hi @vamshi-tg ,

I have not yet test your snippet. But for a very short check, in [the code here](https://github.com/hyperjumptech/grule-rule-engine/blob/622425a813d42b9f2cb0377916201166edea4e9a/engine/GruleEngine.go#L72) the working memory is reset every time you call `engine.Execute()`. I will run your test to see what happen.

**Comment by vamshi-tg** [comment] 2021-01-11 06:24
@newm4n Thanks for the response. The below screenshot of the test result might help you
![image](https://user-images.githubusercontent.com/32225088/104151549-530e1900-5403-11eb-92e4-663a81dc44c3.png)

From the above screenshot, you can see that for the first testData there is 1 matching rule. But for the second testData its shows 0 matching rule.

**Comment by newm4n** [comment] 2021-01-13 06:05
I copied your code snippet as is. Without modification at all. And the result is.

```
=== RUN   TestItems
--- PASS: TestItems (0.00s)
=== RUN   TestItems/0

No. of matching rules: 1
time="2021-01-13T13:01:02+07:00" level=info msg=SampleRule lib=grule-rule-engine package=AST source=GRL
    --- PASS: TestItems/0 (0.00s)
=== RUN   TestItems/1

No. of matching rules: 1
time="2021-01-13T13:01:02+07:00" level=info msg=SampleRule lib=grule-rule-engine package=AST source=GRL
    --- PASS: TestItems/1 (0.00s)
PASS
```

Seems your test went successful.

**Comment by vamshi-tg** [comment] 2021-01-19 14:07
Thanks for responding to this. Could it be because of the run environment. I'm using go version `go1.14.3 on darwin/amd64`. Can you share your environment details? I will try running in the same environment?

**Comment by newm4n** [comment] 2021-01-22 00:13
Um using windows 10 machine, with WSL2 Ubuntu.

**Comment by niallnsec** [comment] 2021-01-22 02:04
I use go on darwin/amd64 also and ran the test function above, which produced the following results:
```
linus@linus-MBP ‹ master ● › : ~/src/grule-rule-engine/examples
[0] % go version
go version go1.15.6 darwin/amd64

linus@linus-MBP ‹ master ● › : ~/src/grule-rule-engine/examples
[0] % go test -run TestItems

No. of matching rules: 1
INFO[0000] SampleRule                                    lib=grule-rule-engine package=AST source=GRL

No. of matching rules: 1
INFO[0000] SampleRule                                    lib=grule-rule-engine package=AST source=GRL
PASS
ok  	github.com/hyperjumptech/grule-rule-engine/examples	0.367s

linus@linus-MBP ‹ master ● › : ~/src/grule-rule-engine/examples
[0] % go1.14.3 test -run TestItems

No. of matching rules: 1
INFO[0000] SampleRule                                    lib=grule-rule-engine package=AST source=GRL

No. of matching rules: 1
INFO[0000] SampleRule                                    lib=grule-rule-engine package=AST source=GRL
PASS
ok  	github.com/hyperjumptech/grule-rule-engine/examples	0.389s

linus@linus-MBP ‹ master ● › : ~/src/grule-rule-engine/examples
[0] %
```

I used the current head of the master branch for the test (tag v1.8.2)

**Comment by niallnsec** [comment] 2021-01-22 02:13
I also had the same result running the test on tagged versions as far back as v1.5.1.

**Comment by newm4n** [comment] 2021-01-26 14:39
Its been 20 days. And unable to reproduce the problem. Im closing.

**Closed by newm4n** 2021-01-26 14:39 UTC

**Comment by fatroom** [comment] 2021-05-10 14:34
I've tried to understand what happened actually. It's correct that working memory is rested on each execution.
But ruleset is not part of WorkingMemory structure (it's part of knowledgebase it self), and once rule retracted it states retracted even working memory is reset. 

Now the question: is knowledgebase should be reset as well on the new execution? or state of the rules should state permanent?
