### ISSUE TITLE
Getting Max cycle reached with 1.6.0

### ISSUE THREAD

**Issue by sourcesoft** [hyperjumptech/grule-rule-engine#108] opened 2020-09-03 00:13 UTC
**Describe the bug**
I just upgraded from 1.5.0 to the latest 1.6.0 and started getting `Max cycle reached`, none of my rules had `Retract`. I'm also using JSON to build the rules, and it works as expected if I add `Retract` to the rules.

**To Reproduce**
1. Use v1.6.0
2. Add one or multiple rule(s) without having Retract at the end for that/those rule(s)
3. See error `Max cycle reached`

**Expected behavior**
Previous versions Retract wasn't mandatory

UPDATE: also getting `warning while adding rule entry : <rulename>. got rule entry <rulename> already exist, possibly already added by antlr listener` which wasn't happening before the upgrade
UPDATE 2: It's also running the THEN statements for all rules that passed instead of just one (highest priority), kinda like what i was looking for [here](https://github.com/hyperjumptech/grule-rule-engine/issues/89)

**Comment by jinagamvasubabu** [comment] 2020-09-03 02:53
Hi @sourcesoft can you ping you ruleset to debug more about this issue ?

1. Possible Suspect for Retract issue Would be: Grule execute the same rule again and again because the WHEN condition keep yielding a valid result. refer this https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/FAQ_en.md

2. Retract is Mandatory ?: `Retract` is not mandatory - Testcases with out `Retract` were passed refer examples section for more info

3. `It's also running the THEN statements for all rules that passed instead of just one (highest priority), kinda like what i was looking for`
I don't think so, because i have written a test just to test this, you can find below here 

```go
package benchmark

import (
	"github.com/hyperjumptech/grule-rule-engine/ast"
	"github.com/hyperjumptech/grule-rule-engine/builder"
	"github.com/hyperjumptech/grule-rule-engine/engine"
	"github.com/hyperjumptech/grule-rule-engine/pkg"
	"testing"
)

type User struct {
	Name    string
	Age     int
	Male    bool
	Address *Address
}

type Address struct {
	HouseNumber string
}

const rule3 = `
rule AgeNameCheck "test" salience 11 {
    when
      User.Name == "Calo" && User.Address.HouseNumber == ""
    then
      User.Name = "Success";
      User.Address.HouseNumber = "H1234";
      Log("AgeNameCheck Executed!!!");
}

rule AgeNameCheckDuplicate "test" salience 10 {
    when
      User.Name == "Calo" && User.Address.HouseNumber == ""
    then
      User.Name = "Calo-Success";
      User.Address.HouseNumber = "H12345";
      Log("AgeNameCheck Executed!!!");
}

rule AgeNameCheck2 "test2" salience 100 {
    when
      (User.Name == "Success") && User.Address.HouseNumber == ""
    then
      User.Name = "Hurray";
      User.Address.HouseNumber = "H12345";
      Log(User.Name);
}
`

func TestMyUser(t *testing.T) {
	address := &Address{
		HouseNumber: "",
	}
	user := &User{
		Name:    "Calo",
		Age:     0,
		Male:    true,
		Address: address,
	}

	dataContext := ast.NewDataContext()
	err := dataContext.Add("User", user)
	if err != nil {
		t.Fatal(err)
	}
	lib := ast.NewKnowledgeLibrary()
	ruleBuilder := builder.NewRuleBuilder(lib)

	err = ruleBuilder.BuildRuleFromResource("Test", "0.1.1", pkg.NewBytesResource([]byte(rule3)))
	if err != nil {
		t.Fatal(err)
	} else {
		kb := lib.NewKnowledgeBaseInstance("Test", "0.1.1")
		eng1 := &engine.GruleEngine{MaxCycle: 100}
		err := eng1.Execute(dataContext, kb)
		if err != nil {
			t.Fatalf("Got error %v", err)
		} else {
			t.Log(user)
		}
		if user.Name != "Success" || user.Address.HouseNumber != "H1234" {
			t.Logf("User should have changed name by rule to Success, but %s", user.Name)
			t.FailNow()
		}
	}
}
```

**Comment by jinagamvasubabu** [comment] 2020-09-03 03:05
Hi @newm4n 
1. `Regarding `warning while adding rule entry : <rulename>. got rule entry <rulename> already exist, possibly already added by antlr listener`
After i debug i found that this `warning` is coming from `RuleBuilder` and possible suspect is we are trying to add rule entry to the knowledgebase even though it exists in knowledgebase because it was got add by the listener as you stated in the warning message.

File: RuleBuilder.go 
```go
grl := listener.Grl
	for _, ruleEntry := range grl.RuleEntries {
		err := kb.AddRuleEntry(ruleEntry)
		if err != nil {
			log.Warnf("warning while adding rule entry : %s. got %s, possibly already added by antlr listener", ruleEntry.RuleName.SimpleName, err.Error())
		}
	}
```

File: GruleParserV2Listener.go
```go
// Already added by the ExitGrl
func (s *GruleV2ParserListener) ExitGrl(ctx *grulev2.GrlContext) {
	if s.StopParse {
		return
	}
	_ = s.Stack.Pop().(*ast.Grl)
	for _, re := range s.Grl.RuleEntries {
		err := s.KnowledgeBase.AddRuleEntry(re)
		if err != nil {
			s.ErrorCallback(err)
		}
	}
}
```


coming to the point, why do we need to have that warning message (because this is keep coming for every rule added into the rule set) and also do we need to add to the knowledgebase even though it got added by `ExitGrl`.

Correct me if i am wrong ?

**Comment by newm4n** [comment] 2020-09-03 12:49
Hi @sourcesoft 

I just committed a new patch v1.6.1 which contains some bug fix as well as sample code verifying that I can not reproduce your issue. You should see the test code in `examples/Issue108_test.go`
The patches release are nothing to do with your issue, that test code just happened to be included in the bug fix.

That test code shows that,

1. The engine is executing rules based on their salience, you can see that on the 1st cycle, all rules is conflicting. Grule correctly execute rules with the highest salience and repeat the evaluation cycle.
2. The engine is not executing all matching rule on any cycle. If you want to go deep, you can see the ExecuteWithContext() function in the `engine/GruleEngine.go` and try to understand the simple logic there in. You will understand that there is no way grule engine executing multiple rules in every cycle with multiple rule in the conflict set (`runnable` list of RuleEntry).
3. All the rule have no `Retract()` function called. All rule just validate it self on each cycle excluding them self from the ConflictSet. 

If you still experience this problem, please provide a gist to reproduce the issue, so we can see, understand and help you better with your issue.

**Comment by sourcesoft** [comment] 2020-09-03 13:09
Thank you for the quick response.

> Possible Suspect for Retract issue Would be: Grule execute the same rule again and again because the WHEN condition keep yielding a valid result. refer this https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/FAQ_en.md

I think you are correct. I'm just not sure why I didn't get this error before. I think the issue was with my rule.

About this bug:
> UPDATE 2: It's also running the THEN statements for all rules that passed instead of just one (highest priority), kinda like what i was looking for here

Sample rules (2 example rules in the same ruleset or knowledge base with the same name)
```
{
    desc: 't1',
    name: 't1',
    salience: 10,
    then: [
      { call: ['Common.CommonSendEmail', { const: 'first subject' }] },
      {
        call: [
          'Retract',
          {
            const: 't1',
          },
        ],
      },
    ],
    when: { eq: [{ call: ['Chat.ChatContains', { const: 'test' }] }, true] },
  }
{
    desc: 't2',
    name: 't2',
    salience: 10,
    then: [
      { call: ['Common.CommonSendEmail', { const: 'another subject' }] },
      {
        call: [
          'Retract',
          {
            const: 't2',
          },
        ],
      },
    ],
    when: { "eq":["Chat.ChatLength","4"]} },
  }
```
Sample facts
```
type CommonFact struct {
	Time int64
}
func (fact *CommonFact) CommonSendEmail(subject string) {
	fmt.Println("email sent! Subject:", subject)
}
```
```
type Chat struct {
	ChatLength   int64
}
func (fact *Chat) ChatContains(t string) bool {
	fmt.Println("chat contains called call", strings.Contains(fact.Text, t))
	return strings.Contains(fact.Text, t)
}
// it's also initialized with:
fact.ChatLength = int64(len(fact.Text))
```
Both actions/then are being executed when fact.Text is `test` passing both rules. Log:
```
...
chat contains called call true
email sent! Subject: another subject
email sent! Subject: sub
```



> I don't think so, because i have written a test just to test this, you can find below here

I'm suspicious of my code too now, so I will try to create a clean minimal reproducible repo/example to see if it's a valid bug or not and then post it here later.

**Comment by sourcesoft** [comment] 2020-09-03 13:46
Just added a test that fails https://github.com/hyperjumptech/grule-rule-engine/pull/111 wondering if this is the expected behaviour. Thank you

**Comment by newm4n** [comment] 2020-09-03 14:16
Ahhh... I think, I understood your problem. Seems you don't understand how RuleEngine works. I suggest you to read [Rule Engine Doc](https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/RuleEngine_en.md#cycle) especially understand the rule evaluation cycle.

Understanding your pull request, For the 1st cycle, your validation in your test should pass without problem, why ? because on the 1st cycle, `Rule1` got executed, thus `SampleFact.Rule1Executed` is `true`. The `SampleFact.Rule2Executed` still `false` on this cycle. After executing `Rule1` on the next cycle, the 2nd, the rule engine evaluate again all rule (which is not retracted). Then it see `Rule2` is matching and execute it as there is no other conflict (`Rule1` already retracted). On this 2nd cycle, the engine executes `Rule2` which makes `SampleFact.Rule2Executed` become `true`. The engine stop its execution as there are no rule to execute, all are retracted.

Then your test went fail as both `SampleFact.Rule1Executed` and `SampleFact.Rule2Executed` are `true`

**Comment by sourcesoft** [comment] 2020-09-03 15:19
Thank you for the explanation, this cleared things up. I'm still reading the source code and getting familiar with it :) 

> instead of executing the satisfied rule's action (the THENs), it adds that rule into a list of rule candidate

When I first read this part of the docs, I thought the outcome of a ruleset being executed once, only one rule could come out. However the next cycle will fire off again. Now I can understand the real purpose of `Retract` and `Complete` too. I remember the first POC i wrote had this behaviour, resulting in [this question](https://github.com/hyperjumptech/grule-rule-engine/issues/89) and the upgrade changed it. Either way I'm happy with the result. Thank you again for the support

**Closed** 2020-09-13 13:41 UTC
